<?php
/**********************************************************************
 *  Author : Sergio Ceron Figueroa (sxceron@laciudadx.com)
 *  Alias  : sxceron
 *  Web    : http://www.dotrow.info
 *  Name   : jShop v1.0
 *  Desc   : Pie de pagina
 *
 ***********************************************************************/
?>
</div>
<div id="footer">
<p><a href="/http://www.laciudadx.com/about">Acerca de nosotros</a> -
<a href="mailto:sxceron@laciudadx.com">Sugerencias</a> - <a
	href="#">Ayuda</a></p>
©2011. Todos los derechos resevados<br>Resolucion minima 1024 x 768 px </div>

<script type="text/javascript">

	/*var messageObj = new DHTML_modalMessage();	// We only create one object of this class

	function displayArticle(url)
	{
		messageObj = new DHTML_modalMessage();
		messageObj.setSource(url+"?cid="+Math.random());
		messageObj.setCssClassMessageBox(false);
		messageObj.setSize(300,200);
		messageObj.display();
	}*/
	</script>
</body>
</html>